version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Script to install necessary dependencies (e.g., Apache, PHP, MySQL)
      timeout: 300
      runas: root
    - location: scripts/start_server.sh          # Script to start the web server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh           # Script to stop any running servers before deployment
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/configure_dvwa.sh       # Script to configure DVWA (e.g., set up database, config files)
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh      # Script to check if the server is running correctly
      timeout: 300
      runas: root
